# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'Hospital',
    'version' : '1.2',
    'summary': 'Hospital',
    'category': 'Hospital Management',
    'author': 'Tien Anh',
    'sequence': -100,
    'description': """""",
    'website': 'https://www.odoo.com/app/hosting',
    'depends' : ['base', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'data/sequence.xml',
        'wizard/cancel_appointment.xml',
        'views/menu.xml',
        'views/patient.xml',
        'views/female_patient.xml',
        'views/appointment.xml',
        'views/patient_tag.xml',
        'views/operation_view.xml',
        'views/odoo_playground.xml',
        'views/res_config_settings_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
}
